language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r app/requirements.txt"
# command to run tests
script: nosetests
before_deploy: cd ..

sudo: false

deploy:
  # Deploy master branch to production environment  on merge (or push)
  - provider: elasticbeanstalk
    access_key_id: AKIAJNTNA6QVLWNUQDCA
    secret_access_key:
      secure: "tpyW/7Gn+7Fx/23sFFp/eH1GT7F2TlBTwcDoam3sRLTlJJz3Grb27dM3E5zSAfx5I8dPBJSbxNk/3MWTanSD++7TVsZKL5tHEkknxr7WFXav+/yRp+T+FPXwv/D6A/T6aahZ+f8wpKoLOLXZCxLIEfagY5oJDQkkyvkE9ESgtVYWLqxrDlo5bNGn3KfBEAFumd13qqW5qYv1G5BuX6fIUb4JzVVcae0qxKiWmO5W05qN0uiSuDl/3mL2kLGE0KU9W3j7raIbcjT6E8EQUCe3H/Qe7DVakesBVIoUU19+d1/AQyUCyecy/Z3otWnvX8SipdbqnS8sTSK145OjjfZH7NJOIEYbKl0sr1PilqHJoXBPvvSu8Y0NZk/6/NkwrIcZDuqYTN2jsiA0/7npKDNolcg+Lm97ybWCRUTSFzsRPJVx+efPT78HsmV8zvS3HYSzWvsjHmantJIFkQgeUrzNvLknviSaG+ejqaBmQJJnjnDUy6+4+f/nZLvf9QSbOnl2mo/akKHVPBsLe/3l1nhFNFpIcMGkL+dOErQwnIMzRiDegUDJgF/Eu2iUUEztpIQfnYOi/Bo4e/2vYsfE3S4UvzMToxafRWLEdiwrkD/Z86+SGrqp/+z8L7inxRqCcThlXqC7M71uh2qfMjVTbLZJU7/dOlhr3PsDxQ2bgrDOpvs="
    region: us-east-1
    app: flask-app-template
    env: FlaskAppTemplateProd
    bucket_name: flask-app-template-deploy
    bucket_path: production
    skip_cleanup: true
    on:
      repo: thehackerati/flask-app-template
      branch: master

  # Deploy staging branch to staging environment  on merge (or push)
  - provider: elasticbeanstalk
    access_key_id: AKIAJNTNA6QVLWNUQDCA
    secret_access_key:
      secure: "tpyW/7Gn+7Fx/23sFFp/eH1GT7F2TlBTwcDoam3sRLTlJJz3Grb27dM3E5zSAfx5I8dPBJSbxNk/3MWTanSD++7TVsZKL5tHEkknxr7WFXav+/yRp+T+FPXwv/D6A/T6aahZ+f8wpKoLOLXZCxLIEfagY5oJDQkkyvkE9ESgtVYWLqxrDlo5bNGn3KfBEAFumd13qqW5qYv1G5BuX6fIUb4JzVVcae0qxKiWmO5W05qN0uiSuDl/3mL2kLGE0KU9W3j7raIbcjT6E8EQUCe3H/Qe7DVakesBVIoUU19+d1/AQyUCyecy/Z3otWnvX8SipdbqnS8sTSK145OjjfZH7NJOIEYbKl0sr1PilqHJoXBPvvSu8Y0NZk/6/NkwrIcZDuqYTN2jsiA0/7npKDNolcg+Lm97ybWCRUTSFzsRPJVx+efPT78HsmV8zvS3HYSzWvsjHmantJIFkQgeUrzNvLknviSaG+ejqaBmQJJnjnDUy6+4+f/nZLvf9QSbOnl2mo/akKHVPBsLe/3l1nhFNFpIcMGkL+dOErQwnIMzRiDegUDJgF/Eu2iUUEztpIQfnYOi/Bo4e/2vYsfE3S4UvzMToxafRWLEdiwrkD/Z86+SGrqp/+z8L7inxRqCcThlXqC7M71uh2qfMjVTbLZJU7/dOlhr3PsDxQ2bgrDOpvs="
    region: us-east-1
    app: flask-app-template
    env: FlaskAppTemplateStaging
    bucket_name: flask-app-template-deploy
    bucket_path: staging
    skip_cleanup: true
    on:
      repo: thehackerati/flask-app-template
      branch: staging
