language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r app/requirements.txt"
# command to run tests
script: nosetests
before_deploy: cd ..

sudo: false

deploy:
  # Deploy master branch to production environment  on merge (or push)
  - provider: elasticbeanstalk
    access_key_id: AKIAJYCV23ZHCMABN6SQ
    secret_access_key:
      "L3aZZw6cGYGOxdQu1IMCj9C2H3FHjKBjzdx9PNqWcsSlipHOZ5iXjg3jTtinNj6cyZO+ftLNZ4V4v9UfZeMjMBiL9XrUFHMT5Wzm9IXr2rpzvAO7Dg6tQVtA6A8/kCc88iqNaPJcjr0F303kDjV5IzgUH/nQLKHsauTFxC9E1RXNs8UPIlwn6p5V+D8ZLRGi3dLdmqQa/z8nIEUNQI1zNKidgi7GPNpOw8oI4RLoWgvzsyXh8zDLnhAX+W/ugDHc16ATGIdSHP7sjK2hBdlQgBMKGHV2t/EWP3aoEui+NJXTgcGZARLmH+Ax/KY68LCgX7HBlMIKgmqqnSoloxJGM1XX1jaJApXWzBN4wqkTTJVx0wTteD8xzEcLm4C1OEpCdnx2lMs/Fzw8a87zgZoIzNxieDE3X0VBaP56bAMUk45s/T/K+90zo6vASVOi4BeT3ok5+u/qndPhDo3u0TfXe/vvOusnWVD5wEMHMq7AbMk6qcnZ6/P/dybMeY4TO4RWaCI0sh6+tkjj2bs8Y6mV8IsLuFxIsW9JgJvCsWOowGH/zn7xtBRQ+IdQkfb4m7zajJwLlDUKUK6CUpIBz03R1WWHQctASXeFaJZAsdei2ZgoJKDZVVQvIQWasZAZGXylGYJVeI7GILAazlXt1ro5ue1fUcomZ/TJLQ6coO6tLhE="
    region: us-east-1
    app: flask-app-template
    env: FlaskAppTemplateProd
    bucket_name: flask-app-template-deploy
    bucket_path: production
    skip_cleanup: true
    on:
      repo: thehackerati/flask-app-template
      branch: master

  # Deploy staging branch to staging environment  on merge (or push)
  - provider: elasticbeanstalk
    access_key_id: AKIAJYCV23ZHCMABN6SQ
    secret_access_key:
      "L3aZZw6cGYGOxdQu1IMCj9C2H3FHjKBjzdx9PNqWcsSlipHOZ5iXjg3jTtinNj6cyZO+ftLNZ4V4v9UfZeMjMBiL9XrUFHMT5Wzm9IXr2rpzvAO7Dg6tQVtA6A8/kCc88iqNaPJcjr0F303kDjV5IzgUH/nQLKHsauTFxC9E1RXNs8UPIlwn6p5V+D8ZLRGi3dLdmqQa/z8nIEUNQI1zNKidgi7GPNpOw8oI4RLoWgvzsyXh8zDLnhAX+W/ugDHc16ATGIdSHP7sjK2hBdlQgBMKGHV2t/EWP3aoEui+NJXTgcGZARLmH+Ax/KY68LCgX7HBlMIKgmqqnSoloxJGM1XX1jaJApXWzBN4wqkTTJVx0wTteD8xzEcLm4C1OEpCdnx2lMs/Fzw8a87zgZoIzNxieDE3X0VBaP56bAMUk45s/T/K+90zo6vASVOi4BeT3ok5+u/qndPhDo3u0TfXe/vvOusnWVD5wEMHMq7AbMk6qcnZ6/P/dybMeY4TO4RWaCI0sh6+tkjj2bs8Y6mV8IsLuFxIsW9JgJvCsWOowGH/zn7xtBRQ+IdQkfb4m7zajJwLlDUKUK6CUpIBz03R1WWHQctASXeFaJZAsdei2ZgoJKDZVVQvIQWasZAZGXylGYJVeI7GILAazlXt1ro5ue1fUcomZ/TJLQ6coO6tLhE="
    region: us-east-1
    app: flask-app-template
    env: FlaskAppTemplateStaging
    bucket_name: flask-app-template-deploy
    bucket_path: staging
    skip_cleanup: true
    on:
      repo: thehackerati/flask-app-template
      branch: staging
