# Start the node.js application server for local development.
appsvr:
  build: ./app
  dockerfile: "Dockerfile.dev"
  volumes:
    - ".:/src/app"
  expose:
    - "5000"
  ports:
    - "5000:5000"    

nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:8080"
  volumes:
    - /www/public
  volumes_from:
    - appsvr
  links:
    - appsvr:appsvr
